### ISSUE TITLE
Increase of AAL with the Risk Mitigation CBA tool 

### ISSUE THREAD

**Issue by xijielu** [worldbank-cdrp/disaster-risk-explorer#21]
In several countries (e.g. Jamaica and Nicaragua) and sub-national units (e.g. Guatemala Alta Verapaz), when replacing/retrofitting a vulnerable building type to a more resilient type, the AAL increased as opposed to being reduced. 

![image](https://user-images.githubusercontent.com/13256498/35818111-29b7d538-0a6d-11e8-895f-f2432505e830.png)
![image](https://user-images.githubusercontent.com/13256498/35818237-7ec964ba-0a6d-11e8-9a7c-702d2456309b.png)
![image](https://user-images.githubusercontent.com/13256498/35818267-9095e164-0a6d-11e8-8dd3-ce91d1a68f09.png)

**Comment by olafveerman** [comment]
This is a hairy issue and a lot is related to how we deal with `null` and `0` values here: https://github.com/worldbank-cdrp/disaster-risk-explorer/blob/develop/app/assets/scripts/utils/building-calc.js#L22

This causes issues with the calculation of `totalBuiltValue` (6a in the Excel sheet) of retrofit, on sub-national level. Every time a relevant building type has a 'Value in USD M' of `0`, the function fetches the values from the national case, causing the big disparities.
Removing the function solves the problem in these cases, but introduces a bug with the calculation of `oldCost` (step 1 in the Excel sheet) in the Replace scenario.

The calculation of `oldCost` is done here: https://github.com/worldbank-cdrp/disaster-risk-explorer/blob/develop/app/assets/scripts/utils/building-calc.js#L84
This requires metro, urban and rural distribution, which is not available for every sub-level. In these cases we do have to use the national values as default.

Now that we have identified one of the main causes of the issue, we should be able to issue a fix for this soon.

## Other cases
There are also a couple of cases that we won't be able to address because the original values in the Excel seem to be erroneous:

- **Jamaica**  
In the original `.xlsm` file, the replacement has the same negative reduction of overall AAL. Tool:  
![image](https://user-images.githubusercontent.com/751330/35943456-1da43e24-0c27-11e8-81a0-a942f7bfce2b.png)
Excel:  
![image](https://user-images.githubusercontent.com/751330/35943464-2db88b44-0c27-11e8-95eb-d92eed995c64.png)
- **Honduras - Islas de Bahia**  
The Excel contains wrong values for retrofit
- **Honduras - Gracias a Dios**  
The Excel contains wrong values for retrofit

cc @drewbo @xijielu

**Comment by xijielu** [comment]
thanks Olaf, I will check on the 3 cases ASAP and get back to you.

@olafveerman

**Comment by xijielu** [comment]
I looked through the spreadsheets; in terms of Jamaica replacement, what happened is that we are replacing a less risky building type to a riskier type, albeit structurally more resilient. James will look into it tonight to provide a solution for that.

For the erroneous values, what happened is that there's no exposure/loss for that building type in that province (see screenshot below). I suggest we disable the selection of these provinces in the drop-down button.
 
![image](https://user-images.githubusercontent.com/13256498/35994253-d4b608c0-0cdd-11e8-8da8-f9390199b704.png)

Due to the same reason, there are several provinces that have negative reduction of AAL because the old building loss is also 0. We need to disable these provinces as well. 

A list of these above cases include: 
For retrofitting, Honduras province 3, 9, 11, 12, 13, and 1; Nicaragua province 15; Panama province 2161, 2162, 2164, and 2166
For replacement, Panama province 2161, 2162, 2164, 2166; Nicaragua province 15.

I will confirm with you once James responds.  

@olafveerman

**Comment by xijielu** [comment]
Hi Olaf,
Here is our conclusion:

For Jamaica replacement, the calculation is correct; what we want to show is in fact when the gov replaces w7 to RM2, it's increasing EQ risk (albeit reducing hurricane risk) and hence the negative reduction of AAL. Can we add a note on the tool interface to explain this?

For the other negative reduction of AALs or null values (because the province does not have corresponding building typology loss - old or new), let's disable these provinces for selection.

Please let me know if it is unclear.

Best
Xijie
@olafveerman

**Comment by olafveerman** [comment]
@xijielu It is relatively simple to disable admin areas for the building calculator, but harder to do so only for retrofitting or replacement. Do you want us to disable those provinces in the building cost calculator until you find a solution to address the underlying data issues?

**Comment by xijielu** [comment]
@olafveerman 
Thanks. 
Let's disable all the provinces that have the aforementioned issues (either replacement or retrofitting). The WB team has reached the consensus.  The negative reduction of AAL should just stand for Jamaica.

**Comment by xijielu** [comment]
@olafveerman 
it does seem like there are more provinces that have negative reduction of AALs than caused by the building loss data being 0. For instance, in Nicaragua, i found only province 15 caused by 0 building loss (either old or new) but about half of the provinces in Nic have negative reduction of AALs.

**Comment by olafveerman** [comment]
@xijielu Just pushed a fix that caused some of the negative values on replacement in Nicaragua. There are  still negative values on Nicaraguan provinces, but these are due to `0` values on the new building values.

**Comment by xijielu** [comment]
@olafveerman 
thanks; if it's due to new building values = 0, let's disable these provinces.

**Comment by olafveerman** [comment]
@xijielu Just pushed fixes with:

- disable the subregions in Nicaragua with negative results
- the following districts in Guatemala have `0` values and will be disabled: Alta Verapaz, Chiquimula, Huehuetenango, Izabal, Peten, and Zacapa
- we've pushed a fix for Panama

Regarding the `NaN` values in Belize. The excel sheet is ambiguous. It mentions that retrofit should be W3 -> W1 (for which there is no distribution data for metro, urban and rural), but the calculations are done for UCB & UCBs -> RM2. Please advice what you want to do here.

**Comment by olafveerman** [comment]
Belize was updated to use UCB & UCBs -> RM2.

All issues seem to be fixed, closing the ticket.
